### ISSUE TITLE
Panels switch back to default visualization

### ISSUE THREAD

**Issue by jfraiberg** [humio/issues#58]
If I am working on a gauge panel in my dashboard and edit the search, it will by default set it to table when I hit save.

**Comment by mwl** [comment]
Thanks for reporting @jfraiberg. We will look into this straight away.

**Comment by Chadtech** [comment]
Hi @jfraiberg would you mind describing the the exact steps you are taking to experience this problem? Something like "I change the query from X to Y and then I click 'save', and then I get this undesired result". I am not able to reproduce the problem yet.

Some queries are not possible with certain visualizations, and under some conditions Humio will switch to a different visualization when you change the query to something that is incompatible with the current visualization. But Im not sure if thats related to what you are describing, because we dont do any visualization changing when you click "save", so I think I just dont understand.

**Comment by jfraiberg** [comment]
step 1 - 

Bring up dashboard with a gauge - 

![h1](https://user-images.githubusercontent.com/24301650/50224536-28f4e480-036c-11e9-9333-0dbb58fa846c.PNG)

step 2 -

click to edit search

step 3 - 

change search (I added the error keyword and hit "run")

After I hit run it changes it to the "automatic" visualization by default - 

![h3](https://user-images.githubusercontent.com/24301650/50224614-55a8fc00-036c-11e9-86ec-008222f21237.PNG)


This causes me to add the extra step of setting it to gauge again.
