### ISSUE TITLE
Feature Request - cross dataspace dashboards

### ISSUE THREAD

**Issue by henrikjohansen** [humio/issues#6]
Currently dashboards are restricted visualise events from a single dataspace which is inefficient for many use-cases. 

It should really be possible to visualise queries across multiple (or all) dataspaces. 

Related to #5

**Comment by anagrius** [comment]
There is no technical reason why this is not possible, and it is something we have already discussed internally. This is very closely related to cross dataspace queries as well. #5

I have thought about making dashboards a top-level concept instead of a per-dataspace thing.

Also having iframes would be nice for embedding widgets from other systems.

**Comment by henrikjohansen** [comment]
I kinda like having stuff grouped by dataspace but it would make sense to have the cross-dataspace ones as a top-level concept.

**Comment by mortengrouleff** [comment]
The current work around for this is to create a view that spans the dataspaces that you need on a dashboard and then create the dashboard in that view.
Dashboards as a top-level concept is on the roadmap.
