### ISSUE TITLE
Feature Request - tweakable query warnings

### ISSUE THREAD

**Issue by henrikjohansen** [humio/issues#9]
We run a distributed Humio cluster across multiple DCs and many of our operations thus incur some additional latency - I would love to have some tuneables that let us define the timeouts for : 

-  Warning: The server nodes 'x', 'y' are not responding.
-  Warning: The server nodes 'x', 'y' are slow.

**Comment by anagrius** [comment]
@mortengrouleff Any thoughts on this?

**Comment by mortengrouleff** [comment]
The timeout values for slow/not responding warnings are currently 20 seconds. 
Hosts get declared "missing" after not responding for 25 consecutive seconds. 
They are thus orders of magnitude larger than any reasonable latency and should as such not need tuning due to e.g 50ms latency from cross-DC traffic.
